# Play TicTacToe Against a Random Agent

Let us fundational reinforcement learning agents to play against a random agent in TicTacToe

In [2]:
# Import Dependencies
import numpy as np
import matplotlib.pyplot as plt
import random

In [5]:
# Create TicTacToe environment
class tictactoe():
    def __init__(self):
        # Create an empty board, where 0 is an empty space, 1 is random player, and 2 is rl player
        shape_board = (3, 3)
        self.state  = np.zeros(shape_board) # Current state in the board
        self.reward = []                    # Instantaneous reward

        self.is_winner  = False
        self.is_draw    = False
        self.is_done    = False      
        self.winner     = 0           
        pass
    
    def check_valid_move(self, move):
        # Check if a move from any of the agents is valid
        is_valid = False
        if (self.state[move] == 0):     # Check if move is in an empty space
            is_valid = True
        return is_valid
    
    def make_move(self, player, move):
        next_player = False

        # Check if move is valid
        is_valid = self.check_valid_move(move)

        if is_valid:
            self.state[move] = player   # Make move
            next_player = True          # Flag for next move

        return next_player

    def check_winner(self):
        #Check if there is a winner
        self.is_winner = False
        self.winner = 0

        win_combinations = np.array([[[0, 0], [0, 1], [0, 2]],  # Winning rows
                                     [[1, 0], [1, 1], [1, 2]],
                                     [[2, 0], [2, 1], [2, 2]],
                                     [[0, 0], [1, 0], [2, 0]],  # Winning columns
                                     [[0, 1], [1, 1], [2, 1]],
                                     [[0, 2], [1, 2], [2, 2]],
                                     [[0, 0], [1, 1], [2, 2]],  # Winning diagonals
                                     [[0, 2], [1, 1], [2, 0]]])
        
        # TODO: FIX!
        for idx in range(win_combinations.shape[1]):
            winner = 0
            is_winner = False

            if all(self.state[win_combinations[:, idx]]):
                is_winner = True
                winner = self.state[win_combinations[:, idx]]
        return winner, is_winner

    def check_done(self):
        # Check if the game is done
        self.is_done = False

        if self.is_winner or self.is_draw:
            self.is_done = True
        
        return self.is_done

    def print_board(self):
        # Print board
        print(self.state)
        pass

In [ ]:
# Create the random agent
class random_agent():
    def __init__(self):
        self.action = []
        pass

    def make_action(self):
        # Make a random movement in the board - Use discrete uniform distribution
        self.action = np.random.randint(3, size=2)
        return self.action

In [ ]:
# Create Q-learning agent
class q_learning_agent():
    def __init__(self):
        self.action = []
        self.q_values = []
        pass
    
    def update_q_values(self):
        pass

    def make_action(self):
        pass


In [7]:
board = tictactoe()

board.print_board()

player = 1
move = (2, 0)
next_player = board.make_move(player, move)

board.print_board()
print(next_player)

player = 2
move = (2, 0)
next_player = board.make_move(player, move)

board.print_board()
print(next_player)

print(board.is_winner())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
True
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
False


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()