# Play TicTacToe Against a Random Agent

Let us fundational reinforcement learning agents to play against a random agent in TicTacToe

In [ ]:
# Import Dependencies
import numpy as np
import matplotlib.pyplot as plt
import random

In [ ]:
# Create TicTacToe environment
class tictactoe():
    def __init__(self):
        # Create an empty board, where 0 is an empty space, 1 is random player, and 2 is rl player
        shape_board = (3, 3)
        self.state  = np.zeros(shape_board) # Current state in the board
        self.reward = []                    # Instantaneous reward
        pass
    
    def check_valid_move(self, move):
        # Check if a move from any of the agents is valid
        is_valid = False
        if (self.state[move] == 0):     # Check if move is in an empty space
            is_valid = True
        return is_valid
    
    def make_move(self, player, move):
        next_player = False

        # Check if move is valid
        is_valid = self.check_valid_move(move)

        if is_valid:
            self.state[move] = player   # Make move
            next_player = True          # Flag for next move

        return next_player

    def is_winner(self):
        is_winner = False

        
        for idx_row in range(2):
            for idx_column in range(2):
                
        pass

    def print_board(self):
        # Print board
        print(self.state)
        pass

In [ ]:
# Create the random agent
class random_agent():
    def __init__(self):
        pass

In [36]:
board = tictactoe()

board.print_board()

player = 1
move = (2, 0)
next_player = board.make_move(player, move)

board.print_board()
print(next_player)

player = 2
move = (2, 0)
next_player = board.make_move(player, move)

board.print_board()
print(next_player)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
True
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
False
